apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sanic-app
  template:
    metadata:
      labels:
        app: sanic-app
    spec:
      containers:
      - name: sanic-app
        image: yxy1109/k8s-sanic:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"