apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: sanic-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.6.0.200-10.6.0.210  # 使用你的内网网段中可用的IP范围+
#    - 1.14.44.190-1.14.44.190 # 腾讯云弹性公网IP
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - sanic-pool