apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: sanic-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.6.0.200-10.6.0.210  # 使用你的内网网段中可用的IP范围
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - sanic-pool
  # 添加nodeSelectors以确保所有节点都能参与负载均衡
  nodeSelectors:
  - matchLabels:
      kubernetes.io/os: linux