# EIP+CLB+Ingress架构优化配置
apiVersion: v1
kind: Service
metadata:
  name: sanic-app-service
  labels:
    app: sanic-app
spec:
  selector:
    app: sanic-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP  # ClusterIP类型，只供集群内部访问
  sessionAffinity: None  # 不在这里做会话保持，在Ingress层处理