name: Build and Deploy to K8s

on:
  push:
    branches: [ main ] # 仅当 main 分支有变更时触发
  workflow_dispatch: # 支持手动触发

env:
  DOCKERHUB_REPO: yxy1109/k8s-sanic  # DockerHub 仓库名

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: 一，获取代码
        uses: actions/checkout@v4

      - name: 二，登录Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 三，生成标签
        id: tag
        run: |
          # 设置时区为 Asia/Shanghai
          export TZ=Asia/Shanghai
          # 使用提交时间戳作为动态标签（例如 20240615-123456）
          echo "TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: 四，镜像构建和推送
        uses: docker/build-push-action@v5
        with:
          context: k8s_sanic/
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ steps.tag.outputs.TAG }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set K8s context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout restart deployment/sanic-app